### ISSUE TITLE
Grupy - ciąg dalszy

### ISSUE THREAD

**Issue by geodotka** [geodotka/ulicznicy#25]
Dodać pola lokalizacji i przy zakładaniu grupy dodać wybór lokalizacji.

**Comment by geodotka** [comment]
@Cosiek, ściagnij tego brancha w wolnej chwili i spróbuj dodać grupę. Na razie nie mam pomysłu, dlaczego jak dodam najpierw areę, to potem nie mogę wstawić na nią punktu (poza areą mogę). Coś jest z tym bindMapOnClick nie tak, to jest zdecydowanie źle wywoływane.
Aktualny stan TODO:
 - [ ] dodać info, co jak nie znajdzie takiego adresu, a raczej status nie jest OK
 - [ ] po walidacji formularza na pewno znikną te punkty na mapie -> fuj, trzeba je na starcie poustawiać
 - [ ] schować inputa (a ten drugi od arei chyba nie był chowany przeze mnie, a gdzieś się podział. Jest gdzieś, lecz nie wiadomo gdzie świat, w którym baśń ta dzieje się")
 - [ ] zrobić ładne wyświetlanie grupy po dodaniu
 - [ ] zmienić początkową lokalizację - umieściłam ją na placu narutowicza i zmieniłam zoom, bo już nie chciało mi się aż tak przybliżać

Już wiem, po co może być punkt wstawienia. Chociażby do zoomowania mapy, gdy wchodzimy na grupę i chcemy pokazać jej lokalizację. Choć pewnie jest na to inny sposób na podstawie samego poligonu. Wymyślę jeszcze coś. Spokojna głowa.

**Comment by geodotka** [comment]
@Cosiek, podpowiedz. Jak mam tworzenie grupy i tam mapa + markery i wyświetlanie danych grupy: mapa + markery, przy czym w pierwszym przypadku zaznaczamy na mapie sami, a w drugim tylko wyświetlamy, to oddzielne :coffee: , czy wrzucić jakoś to do jednego wora, ale z głową?

**Comment by Cosiek** [comment]
jeden wór - piszesz jedną fukcję która renderuje wszystko co jest narysowane na mapie (w zależności od tego co masz w VARS), więc potrzebne różne funkcje które to tam wrzucą, ale muszą mieć dostęp do renderującej.
Ściągam i sprawdzam.
