### ISSUE TITLE
Dodawanie trasy - spięcie widoku z modelem

### ISSUE THREAD

**Issue by Cosiek** [geodotka/ulicznicy#40]
W dużym skrócie - żeby dało się dodać nową trasę ze strony.

**Comment by Cosiek** [comment]
@geodotka - jak sądzisz, lepiej tradycyjny form czy AJAX?

**Comment by Cosiek** [comment]
Szybciej piszę niż myślę - AJAX.

**Comment by geodotka** [comment]
@Cosiek , ależ ja mam refleks - AJAX, bo łatwiej ogarnąć błędy w formularzu

**Comment by Cosiek** [comment]
:smile:
