### ISSUE TITLE
Testy dla konkretnych appek

### ISSUE THREAD

**Issue by Cosiek** [geodotka/ulicznicy#55]
Aktualnie przez faba można odpalić testy tylko dla całej aplikacji. Fajnie by było gdybym mógł sobie odpalić test tylko dla accounts, lub tylko dla matchmakera.

Do popdpatrzenia w fabfile na bw.

**Comment by Cosiek** [comment]
Właśnie zauważyłem, że django nose jest ustawiony jako testruner, a dodatkowo ucisza printy w testach. Chciałbym mieć możliwość powrotu do normalnego testrunera.

**Comment by geodotka** [comment]
Nic z tego nie rozumiem, ale jak siądę do zadania, to pewnie się rozjaśni w głowie.

**Comment by Cosiek** [comment]
chcę móc wpisać w konsolę `fab test` - i odpalić wszystkie testy, albo `fab test accounts` i żeby odpaliły się tylko te dla accounts (z pominięciem tych z matchmaker).

> Nic z tego nie rozumiem, ale jak siądę do zadania, to pewnie się rozjaśni w głowie.

:ok: :smile:

**Comment by geodotka** [comment]
To zrozumiałam, tego pozostałego nie.
